export const GET_LIBRARIES_BEGIN = 'GET_LIBRARIES_BEGIN';
export const GET_LIBRARIES_SUCCESS = 'GET_LIBRARIES_SUCCESS';
export const GET_LIBRARIES_ERROR = 'GET_LIBRARIES_ERROR';

export const CREATE_LIBRARY_BEGIN = 'CREATE_LIBRARY_BEGIN';
export const CREATE_LIBRARY_SUCCESS = 'CREATE_LIBRARY_SUCCESS';
export const CREATE_LIBRARY_ERROR = 'CREATE_LIBRARY_ERROR';

export const UPDATE_LIBRARY_BEGIN = 'UPDATE_LIBRARY_BEGIN';
export const UPDATE_LIBRARY_SUCCESS = 'UPDATE_LIBRARY_SUCCESS';
export const UPDATE_LIBRARY_ERROR = 'UPDATE_LIBRARY_ERROR';

export const DELETE_LIBRARY_BEGIN = 'DELETE_LIBRARY_BEGIN';
export const DELETE_LIBRARY_SUCCESS = 'DELETE_LIBRARY_SUCCESS';
export const DELETE_LIBRARY_ERROR = 'DELETE_LIBRARY_ERROR';

export const GET_STUDENTS_BEGIN = 'GET_STUDENTS_BEGIN';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_ERROR = 'GET_STUDENTS_ERROR';

export const CREATE_STUDENT_BEGIN = 'CREATE_STUDENT_BEGIN';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_ERROR = 'CREATE_STUDENT_ERROR';

export const UPDATE_STUDENT_BEGIN = 'UPDATE_STUDENT_BEGIN';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_ERROR = 'UPDATE_STUDENT_ERROR';

export const DELETE_STUDENT_BEGIN = 'DELETE_STUDENT_BEGIN';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_ERROR = 'DELETE_STUDENT_ERROR';

export const GET_BOOKS_BEGIN = 'GET_BOOKS_BEGIN';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_ERROR = 'GET_BOOKS_ERROR';

export const CREATE_BOOK_BEGIN = 'CREATE_BOOK_BEGIN';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const CREATE_BOOK_ERROR = 'CREATE_BOOK_ERROR';

export const UPDATE_BOOK_BEGIN = 'UPDATE_BOOK_BEGIN';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_ERROR = 'UPDATE_BOOK_ERROR';

export const DELETE_BOOK_BEGIN = 'DELETE_BOOK_BEGIN';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_ERROR = 'DELETE_BOOK_ERROR';
