export const GET_LIBRARIES_BEGIN = 'GET_LIBRARIES_BEGIN';
export const GET_LIBRARIES_SUCCESS = 'GET_LIBRARIES_SUCCESS';
export const GET_LIBRARIES_ERROR = 'GET_LIBRARIES_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const CREATE_LIBRARY_BEGIN = 'CREATE_LIBRARY_BEGIN';
export const CREATE_LIBRARY_SUCCESS = 'CREATE_LIBRARY_SUCCESS';
export const CREATE_LIBRARY_ERROR = 'CREATE_LIBRARY_ERROR';

export const SET_EDIT_LIBRARY = 'SET_EDIT_LIBRARY';
export const GET_LIBRARY_ID = 'GET_LIBRARY_ID';

export const EDIT_LIBRARY_BEGIN = 'EDIT_LIBRARY_BEGIN';
export const EDIT_LIBRARY_SUCCESS = 'EDIT_LIBRARY_SUCCESS';
export const EDIT_LIBRARY_ERROR = 'EDIT_LIBRARY_ERROR';

export const DELETE_LIBRARY = 'DELETE_LIBRARY';

export const ADD_TO_LIBRARY_BEGIN = 'ADD_TO_LIBRARY_BEGIN';
export const ADD_TO_LIBRARY_SUCCESS = 'ADD_TO_LIBRARY_SUCCESS';
export const ADD_TO_LIBRARY_ERROR = 'ADD_TO_LIBRARY_ERROR';

export const ADD_BOOK_TO_LIBRARY_BEGIN = 'ADD_BOOK_TO_LIBRARY_BEGIN';
export const ADD_BOOK_TO_LIBRARY_SUCCESS = 'ADD_BOOK_TO_LIBRARY_SUCCESS';
export const ADD_BOOK_TO_LIBRARY_ERROR = 'ADD_BOOK_TO_LIBRARY_ERROR';

export const DELETE_FROM_LIBRARY_BEGIN = 'DELETE_FROM_LIBRARY_BEGIN';
export const DELETE_FROM_LIBRARY_SUCCESS = 'DELETE_FROM_LIBRARY_SUCCESS';
export const DELETE_FROM_LIBRARY_ERROR = 'DELETE_FROM_LIBRARY_ERROR';

export const DELETE_BOOK_FROM_LIBRARY_BEGIN = 'DELETE_BOOK_FROM_LIBRARY_BEGIN';
export const DELETE_BOOK_FROM_LIBRARY_SUCCESS =
  'DELETE_BOOK_FROM_LIBRARY_SUCCESS';
export const DELETE_BOOK_FROM_LIBRARY_ERROR = 'DELETE_BOOK_FROM_LIBRARY_ERROR';

export const GET_STUDENTS_BEGIN = 'GET_STUDENTS_BEGIN';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_ERROR = 'GET_STUDENTS_ERROR';

export const CREATE_STUDENT_BEGIN = 'CREATE_STUDENT_BEGIN';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_ERROR = 'CREATE_STUDENT_ERROR';

export const GET_STUDENT_ID = 'GET_STUDENT_ID';

export const SET_EDIT_STUDENT = 'SET_EDIT_STUDENT';
export const EDIT_STUDENT_BEGIN = 'EDIT_STUDENT_BEGIN';
export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENT_SUCCESS';
export const EDIT_STUDENT_ERROR = 'EDIT_STUDENT_ERROR';

export const ADD_BOOK_TO_STUDENT_BEGIN = 'ADD_BOOK_TO_STUDENT_BEGIN';
export const ADD_BOOK_TO_STUDENT_SUCCESS = 'ADD_BOOK_TO_STUDENT_SUCCESS';
export const ADD_BOOK_TO_STUDENT_ERROR = 'ADD_BOOK_TO_STUDENT_ERROR';

export const DELETE_BOOK_FROM_STUDENT_BEGIN = 'DELETE_BOOK_FROM_STUDENT_BEGIN';
export const DELETE_BOOK_FROM_STUDENT_SUCCESS =
  'DELETE_BOOK_FROM_STUDENT_SUCCESS';
export const DELETE_BOOK_FROM_STUDENT_ERROR = 'DELETE_BOOK_FROM_STUDENT_ERROR';

export const DELETE_STUDENT = 'DELETE_STUDENT';

export const GET_BOOKS_BEGIN = 'GET_BOOKS_BEGIN';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_ERROR = 'GET_BOOKS_ERROR';

export const CREATE_BOOK_BEGIN = 'CREATE_BOOK_BEGIN';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const CREATE_BOOK_ERROR = 'CREATE_BOOK_ERROR';

export const EDIT_BOOK_BEGIN = 'EDIT_BOOK_BEGIN';
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export const EDIT_BOOK_ERROR = 'EDIT_BOOK_ERROR';

export const DELETE_BOOK_BEGIN = 'DELETE_BOOK_BEGIN';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_ERROR = 'DELETE_BOOK_ERROR';
